### ISSUE TITLE
Merge with calcinai/xero-php

### ISSUE THREAD

**Issue by mhlavac** [elliotchance/xero-api#6]
Hi @elliotchance, first of all great effort on improving Xero API.

Did you see this library https://github.com/calcinai/xero-php ? Your repository is more favorite, but  calcinai/xero-php looks like a nicer approach with all of these nicely generated classes that makes working with API response really easy.

**Comment by elliotchance** [comment]
Hi @mhlavac, theres actually nothing in my library except for composer support and a few release tags. I didn't want to change any code that would cause merge conflicts when I pulled in the latest from the official repo.

I was going to delete this repo when xero put composer support into their main repo. Which they have done but they still don't get it and I'm sick of fighting for it - especially when other developers have done such a great job with brand new libraries like calcinai/xero-php.

This can't be merged into calcinai/xero-php because they weren't forked from the same repo. I haven't added any useful code to my fork.

**Comment by mhlavac** [comment]
@elliotchance Xero approach in this case is unfortunate.

Can you at least mention them in README.md?

I am afraid Xero will never add semver. I still don't get why it was so hard to add composer.json in the first place.
